from enum import Enum, auto


class TwitchNoticeType(Enum):

    ANNOUNCEMENT = auto()
    BITS_BADGE_TIER = auto()
    CHARITY_DONATION = auto()
    COMMUNITY_SUB_GIFT = auto()
    GIFT_PAID_UPGRADE = auto()
    MODIVERSARY = auto()
    PAY_IT_FORWARD = auto()
    PRIME_PAID_UPGRADE = auto()
    RAID = auto()
    RE_SUB = auto()
    SHARED_CHAT_ANNOUNCEMENT = auto()
    SHARED_CHAT_COMMUNITY_SUB_GIFT = auto()
    SHARED_CHAT_GIFT_PAID_UPGRADE = auto()
    SHARED_CHAT_MODIVERSARY = auto()
    SHARED_CHAT_PAY_IT_FORWARD = auto()
    SHARED_CHAT_PRIME_PAID_UPGRADE = auto()
    SHARED_CHAT_RAID = auto()
    SHARED_CHAT_RE_SUB = auto()
    SHARED_CHAT_SUB = auto()
    SHARED_CHAT_SUB_GIFT = auto()
    SUB = auto()
    SUB_GIFT = auto()
    UNKNOWN = auto()
    UN_RAID = auto()
    WATCH_STREAK = auto()
