from enum import Enum, auto


class SoundAlert(Enum):

    AIR_STRIKE = auto()
    BEAN = auto()
    CHEER = auto()
    CLICK_NAVIGATION = auto()
    FOLLOW = auto()
    GRENADE_1 = auto()
    GRENADE_2 = auto()
    GRENADE_3 = auto()
    HYPE_TRAIN = auto()
    JACKPOT = auto()
    LAUNCH_AIR_STRIKE = auto()
    MEGA_GRENADE_1 = auto()
    MEGA_GRENADE_2 = auto()
    MEGA_GRENADE_3 = auto()
    POINT_REDEMPTION_01 = auto()
    POINT_REDEMPTION_02 = auto()
    POINT_REDEMPTION_03 = auto()
    POINT_REDEMPTION_04 = auto()
    POINT_REDEMPTION_05 = auto()
    POINT_REDEMPTION_06 = auto()
    POINT_REDEMPTION_07 = auto()
    POINT_REDEMPTION_08 = auto()
    POINT_REDEMPTION_09 = auto()
    POINT_REDEMPTION_10 = auto()
    POINT_REDEMPTION_11 = auto()
    POINT_REDEMPTION_12 = auto()
    POINT_REDEMPTION_13 = auto()
    POINT_REDEMPTION_14 = auto()
    POINT_REDEMPTION_15 = auto()
    POINT_REDEMPTION_16 = auto()
    PREDICTION = auto()
    RAID = auto()
    RANDOM_FROM_DIRECTORY = auto()
    SPLAT = auto()
    SUBSCRIBE = auto()
