from enum import Enum, auto


class SoundAlert(Enum):

    BEAN = auto()
    CHEER = auto()
    CLICK_NAVIGATION = auto()
    JACKPOT = auto()
    POINT_REDEMPTION_01 = auto()
    POINT_REDEMPTION_02 = auto()
    POINT_REDEMPTION_03 = auto()
    POINT_REDEMPTION_04 = auto()
    POINT_REDEMPTION_05 = auto()
    POINT_REDEMPTION_06 = auto()
    POINT_REDEMPTION_07 = auto()
    POINT_REDEMPTION_08 = auto()
    POINT_REDEMPTION_09 = auto()
    POINT_REDEMPTION_10 = auto()
    POINT_REDEMPTION_11 = auto()
    POINT_REDEMPTION_12 = auto()
    POINT_REDEMPTION_13 = auto()
    POINT_REDEMPTION_14 = auto()
    POINT_REDEMPTION_15 = auto()
    POINT_REDEMPTION_16 = auto()
    RAID = auto()
    RANDOM_FROM_DIRECTORY = auto()
    SUBSCRIBE = auto()
    TNT_1 = auto()
    TNT_2 = auto()
    TNT_3 = auto()
